# Generated by Django 6.0.7 on 2026-07-09 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Overlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clip', models.PositiveSmallIntegerField(choices=[(1, 'Clip 1  ·  0–5s'), (2, 'Clip 2  ·  5–10s'), (3, 'Clip 3  ·  10–15s'), (4, 'Clip 4  ·  15–20s'), (5, 'Clip 5  ·  20–25s'), (6, 'Clip 6  ·  25–30s'), (7, 'Clip 7  ·  30–35s')], help_text='Which 5-second clip of the video this message floats over.')),
                ('message', models.CharField(help_text='The main line shown inside the cloud.', max_length=120)),
                ('submessage', models.CharField(blank=True, help_text='Optional smaller line beneath the main message.', max_length=160)),
                ('position', models.CharField(choices=[('top', 'Top'), ('center', 'Center'), ('bottom', 'Bottom')], default='center', help_text='Where on the screen the cloud appears.', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Untick to hide this message without deleting it.')),
            ],
            options={
                'verbose_name': 'Text overlay',
                'verbose_name_plural': 'Text overlays',
                'ordering': ['clip'],
            },
        ),
    ]
