# Generated by Django 6.0.7 on 2026-07-09 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Circle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(choices=[(1, 'Circle 1'), (2, 'Circle 2'), (3, 'Circle 3'), (4, 'Circle 4'), (5, 'Circle 5'), (6, 'Circle 6'), (7, 'Circle 7'), (8, 'Circle 8'), (9, 'Circle 9'), (10, 'Circle 10'), (11, 'Circle 11'), (12, 'Circle 12')], help_text='Which of the 12 circles (1–12) this object fills.', unique=True)),
                ('title', models.CharField(blank=True, help_text='Optional heading shown at the top of the popup.', max_length=80)),
                ('image', models.FileField(help_text='Image shown as the circle itself (required).', upload_to='circles/images/')),
                ('audio', models.FileField(blank=True, help_text='Optional audio to play in the popup.', upload_to='circles/audio/')),
                ('video', models.FileField(blank=True, help_text='Optional video to play in the popup.', upload_to='circles/video/')),
                ('message', models.TextField(blank=True, help_text='Optional written message to show in the popup.')),
            ],
            options={
                'verbose_name': 'Memory circle',
                'verbose_name_plural': 'Memory circles',
                'ordering': ['position'],
            },
        ),
    ]
