# Generated by Django 6.0.7 on 2026-07-09 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cel', '0002_circle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='overlay',
            options={'ordering': ['start'], 'verbose_name': 'Text overlay', 'verbose_name_plural': 'Text overlays'},
        ),
        migrations.RemoveField(
            model_name='overlay',
            name='clip',
        ),
        migrations.RemoveField(
            model_name='overlay',
            name='position',
        ),
        migrations.AddField(
            model_name='overlay',
            name='audio',
            field=models.FileField(blank=True, help_text='Optional MP3 to autoplay during the video.', upload_to='overlay_audio/'),
        ),
        migrations.AddField(
            model_name='overlay',
            name='audio_end',
            field=models.FloatField(blank=True, help_text='Optional second to stop the music. Leave blank to play until it ends.', null=True),
        ),
        migrations.AddField(
            model_name='overlay',
            name='audio_start',
            field=models.FloatField(default=0, help_text='Second of the video at which the music starts playing.'),
        ),
        migrations.AddField(
            model_name='overlay',
            name='end',
            field=models.FloatField(default=5, help_text='Second of the video at which the text disappears.'),
        ),
        migrations.AddField(
            model_name='overlay',
            name='start',
            field=models.FloatField(default=0, help_text='Second of the video at which the text appears.'),
        ),
        migrations.AlterField(
            model_name='overlay',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Untick to hide this row without deleting it.'),
        ),
        migrations.AlterField(
            model_name='overlay',
            name='message',
            field=models.CharField(blank=True, help_text='The main line shown in the cloud (leave blank for audio-only).', max_length=120),
        ),
    ]
